"""CLI option and command constants."""

HELP_OPTION_NAMES = ("-h", "--help")

TARGET_OPTION_FLAGS = ("--target", "-t")
LANGUAGE_OPTION_FLAGS = ("--language", "-l")
LEVELS_OPTION_FLAGS = ("--levels",)
GOOGLE_USER_DATA_DIR_OPTION_FLAGS = ("--google-user-data-dir",)
STATE_DIR_OPTION_FLAGS = ("--state-dir",)
IGNORE_CHECKPOINT_OPTION_FLAGS = ("--ignore-checkpoint",)
DEBUG_SYNC_FAILURES_OPTION_FLAGS = ("--debug-sync-failures",)
MAX_PAGES_OPTION_FLAGS = ("--max-pages",)
MAX_ROWS_PER_PAGE_OPTION_FLAGS = ("--max-rows-per-page",)
HEADED_OPTION_FLAGS = ("--headed/--headless",)
CRAWL_DELAY_OPTION_FLAGS = ("--crawl-delay",)
MAPS_DELAY_OPTION_FLAGS = ("--maps-delay",)
MAX_SAVE_RETRIES_OPTION_FLAGS = ("--max-save-retries",)
DRY_RUN_OPTION_FLAGS = ("--dry-run",)
SANDBOX_OPTION_FLAGS = ("--sandbox",)
MAPS_PROBE_ONLY_OPTION_FLAGS = ("--maps-probe-only",)
MAPS_PROBE_ROWS_FILE_OPTION_FLAGS = ("--maps-probe-rows-file",)
RECORD_FIXTURES_DIR_OPTION_FLAGS = ("--record-fixtures-dir",)
LIST_NAME_PREFIX_OPTION_FLAGS = ("--list-name-prefix",)
LIST_NAME_TEMPLATE_OPTION_FLAGS = ("--list-name-template",)
ON_MISSING_LIST_OPTION_FLAGS = ("--on-missing-list",)
IGNORE_EXISTING_LISTS_CHECK_OPTION_FLAGS = ("--ignore-existing-lists-check",)
LOGIN_TIMEOUT_OPTION_FLAGS = ("--login-timeout",)
CA_BUNDLE_OPTION_FLAGS = ("--ca-bundle", "-b")
INSECURE_OPTION_FLAGS = ("--insecure", "-k")
