"""Runtime defaults and sync guardrails."""

DEFAULT_SLEEP_SECONDS = 0.3
DEFAULT_LANGUAGE = "en"
REQUEST_TIMEOUT_SECONDS = 15
HTTP_MAX_FETCH_RETRIES = 3
HTTP_RETRY_BASE_DELAY_SECONDS = 1.0
HTTP_RETRYABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})

DEFAULT_SYNC_DELAY_SECONDS = 0.3
DEFAULT_MAX_SAVE_RETRIES = 1
DEFAULT_LOGIN_TIMEOUT_SECONDS = 240
DEFAULT_GOOGLE_USER_DATA_DIR = "~/.michelin-gmaps-profile"
DEFAULT_MAX_PAGES = 0
DEFAULT_MAX_ROWS_PER_PAGE = 0
SANDBOX_DEFAULT_MAX_PAGES = 1
DEFAULT_RECORD_FIXTURES_DIR = ""

DEFAULT_LIST_NAME_PREFIX = ""
SANDBOX_LIST_NAME_PREFIX = "[TEST] "
LIST_NAME_TEMPLATE_PLACEHOLDERS = (
    "{prefix}",
    "{scope}",
    "{level}",
    "{level_slug}",
    "{level_label}",
    "{level_badge}",
)
DEFAULT_LIST_NAME_TEMPLATE = "{prefix}{scope} Michelin {level_badge}"
LANGUAGE_LIST_NAME_TEMPLATE_OVERRIDES = {
    "zh_TW": "{prefix}{scope} \u7c73\u5176\u6797 {level_badge}",
}

MISSING_LIST_POLICY_STOP = "stop"
MISSING_LIST_POLICY_CONTINUE = "continue"
MISSING_LIST_POLICY_CHOICES = (
    MISSING_LIST_POLICY_STOP,
    MISSING_LIST_POLICY_CONTINUE,
)
DEFAULT_MISSING_LIST_POLICY = MISSING_LIST_POLICY_CONTINUE
